grades = [[5, 3, 3, 5, 4], [2, 2, 2, 3], [4, 5, 5, 2], [4, 4, 3], [5, 5, 5, 4, 5]]
students = sorted({'Johnny', 'Bilbo', 'Steve', 'Khendrik', 'Aaron'})
marks = dict(zip(students, grades))
a = (sum(marks['Aaron']))
r = (len(marks['Aaron']))
marks.update({'Aaron': a/r})
b = (sum(marks['Bilbo']))
t = (len(marks['Bilbo']))
marks.update({'Bilbo': b/t})
c = (sum(marks['Johnny']))
y = (len(marks['Johnny']))
marks.update({'Johnny': c/y})
d = (sum(marks['Khendrik']))
u = (len(marks['Khendrik']))
marks.update({'Khendrik': d/u})
e = (sum(marks['Steve']))
i = (len(marks['Steve']))
marks.update({'Steve': e/i})
print(marks)
